spring:
  jpa:
    database: mysql
    show-sql: true
#    hibernate:
#      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/dental
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: localhost
    port: 25
    username: xxxx
    password: xxxx
server:
  port: 6616
  